@BASE_API_URL = http://localhost:3000

#### 
# @name user_login
curl -X 'POST' \
  '{{BASE_API_URL}}/auth/login' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
    "password": "12345678",
    "email": "user1@yopmail.com"
  }'

@USER_JWT                = {{user_login.response.body.accessToken}}

#### tenants create new a company
curl -X 'POST' \
  '{{BASE_API_URL}}/tenants/create-company' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "companyName": "companyName1",
  "user": {
    "name": "name1",
    "password": "12345678",
    "email": "user1@yopmail.com"
  }
}'

##### products
curl -X 'GET' \
  '{{BASE_API_URL}}/products' \
  -H 'authorization: Bearer {{USER_JWT}}' \
  -H 'X-TENANT-ID: 925Fx6uN6vPO'
